# Generated by Django 5.2.9 on 2026-01-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='data_cricacao',
            new_name='data_criacao',
        ),
    ]
